# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23a5df6ffa84b1b25f6b1dc6282bd29d1325bda67a3449a5a88140dc232a2a8a36ec613db52ce887d631f39240141533cccc332a3673bcf4496044fda5efdaef

test:
  secret_key_base: 79709ab7660f34d9b8880bfc5db1ad283602948a24f8656eb84cc0d4c63a095c304712d57b7cf4b268645dff7f9905a1c4cfa3de63371a25f0a5719da2758a57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
